# Generated by Django 4.2.11 on 2024-04-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname1', models.CharField(max_length=20)),
                ('number1', models.CharField(max_length=4)),
                ('expect1', models.CharField(max_length=4)),
                ('nickname2', models.CharField(max_length=20)),
                ('number2', models.CharField(max_length=4)),
                ('expect2', models.CharField(max_length=4)),
            ],
        ),
    ]
